ActiveStorage による画像アップロードを実装（テストを含む）
unstoppa61e/fjord-books_app pull request #4
Opened 2021-09-07 07:28 UTC by monoue

2021-09-13 12:43 UTC, u1tnk requested changes
細かいところ二点コメントしましたが問題無いレベルなのでOKです 🙆‍♀️

2021-09-13 12:43 UTC, u1tnk commented on test/controllers/books_controller_test.rb
> +#
コメントアウトしたものは残す必要は無いですよ。

2021-09-13 12:43 UTC, u1tnk commented on test/fixtures/users.yml
> +  encrypted_password: <%= Devise::Encryptor.digest(User, 'password') %>
これ実際にログインするわけじゃないですよね？でしたら単にランダムな文字列で良いと思いますよ。

2021-09-13 12:45 UTC, u1tnk reviewed
Approve取り消すほどでも無いですが、気づいたのが一点。

要件では `jpg`を通すようになっていますが、 `jpeg`を許可しているようです。
動作確認で手元の `jpg`ファイルアップロードしたら動かなくてハマったので気づきました 😅

2021-09-14 01:14 UTC, unstoppa61e commented on test/controllers/books_controller_test.rb
> +#
削除させて頂きました🙏

2021-09-14 01:14 UTC, unstoppa61e commented on test/fixtures/users.yml
> +  encrypted_password: <%= Devise::Encryptor.digest(User, 'password') %>
Faker で対処させて頂きました🙏

2021-09-14 01:16 UTC, unstoppa61e commented
`jpeg`から`jpg`に修正させて頂きました🙏

2021-12-03 06:13 UTC, merged